### ISSUE TITLE
Scrollbars missing

### ISSUE THREAD

**Issue by xfra35** [ybogdanov/history-timeline#13]
Hi, nice project!

There's a small issue on Firefox (I haven't tried Chrome): horizontal and vertical scrollbars don't appear, which makes it impossible to read the whole timeline.

Cheers

**Comment by ybogdanov** [comment]
Thanks, @xfra35! Will take a look.
Chrome works well.

**Comment by ybogdanov** [comment]
@xfra35 check it!

**Comment by xfra35** [comment]
Well done! Thanks :+1:
