### ISSUE TITLE
Remove Ani Lorak

### ISSUE THREAD

**Issue by k-bx** [ybogdanov/history-timeline#18]
It's disgusting seeing her there.

**Comment by ybogdanov** [comment]
LOL, but I will not do this, sorry. The data set is provided by [Pantheon](http://pantheon.media.mit.edu/) as is, and I think it is fair not to manipulate the list individually unless we come up with our own rating system. However, current popularity algorithm is not as bad. You can read the description [here](http://pantheon.media.mit.edu/methods) (look for "Measures of Global Historical Popularity" chapter).

**Comment by k-bx** [comment]
I see, thanks. As I understand, she's included because wiki article about her is translated into >25 languages. I think this metric could be improved, will try to find a place to discuss that with Pantheon guys.

**Comment by k-bx** [comment]
Lol Germans :) (looking at page views)

```
➜  antilorak git:(master) ✗ stack exec antilorak
az: 503.0
bn: 128.0
be: 167.0
ca: 213.0
cs: 933.0
de: 6094.0
el: 638.0
es: 1750.0
fr: 1032.0
ga: 81.0
hy: 843.0
hr: 123.0
id: 299.0
it: 992.0
ka: 599.0
lv: 466.0
lb: 305.0
lt: 861.0
hu: 269.0
mk: 119.0
mn: 159.0
na: 170.0
nl: 665.0
oc: 98.0
pl: 2924.0
pt: 460.0
ru: 296025.0
sco: 510.0
sq: 92.0
sr: 348.0
sh: 209.0
fi: 536.0
sv: 492.0
tr: 1892.0
tw: 206.0
uk: 19970.0
```

**Comment by ybogdanov** [comment]
:)

**Comment by k-bx** [comment]
This will be the last spam from me here. Just FYI, sending a letter to Pantheon guys with a link to https://github.com/k-bx/antilorak project and a clear evidence that Ani Lorak is indeed only popular in Russia (in comparison with other pageviews), so there's a high doubt in her significance in Global History.
