### ISSUE TITLE
Character countries marked wrong.

### ISSUE THREAD

**Issue by robbphoenix** [ybogdanov/history-timeline#2]
Great work.

A small issue, Akbar,  Shah Jahan, Guru Nanak, Porus, Sonia Gandhi, Mother Teresa are quintessentially Indian figures. They have been marked wrongly in your table.

From Wiki page quote:

Akbar:
"Akbar the Great (Urdu: Akbar-e-Azam; literally "Great the Great"),[8] was Mughal Emperor from 1556 until his death. He was the third and one of the greatest rulers of the Mughal Dynasty in India."

Shah Jahan was the son of Jahangir (who is marked correctly as Indian). 

Regarding Guru Nanak (the founder of Sikhism) and Porus who were born in Punjab (Pakistan as a notion didn't exist them, everything East of Indus used to be called India), Pakistan only came to exist after the British divided "British India" in 1948. Marking Guru Nanak Singh (founder of Sikhism) as Pakistani would be as absurd as making Manmohan Singh (former Indian premier and another Sikh). out to be Pakistani (who was also born there before partition) . 

Porus was referred to in his letters as an Indian king by Alexander himself.

Sonia Gandhi and Mother Teresa, despite being born abroad are Indian citizens and would be buried in India, in a similar vien George Orwell and Rudyard Kipling, despite being born in British India are British citizens, buried in Britain.

**Comment by ybogdanov** [comment]
Hi @robbphoenix, thanks for the corrections!
I take the country data from [Pantheon](http://pantheon.media.mit.edu/) as they provide it, and so far as I can tell, they give a birth country. But luckily fixing it in the timeline is easy. If you are interested in contributing data, I can help you to setup the workflow. Are you familiar with Github pull requests mechanics? I can write an instruction how to do a content contribution so you can fix it yourself and I will merge it to the project then.

**Comment by robbphoenix** [comment]
Since Indian historical figures are severely underrepresented, I would like to help in that regard.

Unfortunately Github mechanics are completely alien to me (I'm an Aerospace engg. with only a basic background in programming). If you could give sufficiently detailed instructions however, I will see what I can do.

**Comment by robbphoenix** [comment]
Again great work, this is going to help a lot of people!

**Comment by ybogdanov** [comment]
First, [fork the repository](https://help.github.com/articles/fork-a-repo/) so you have your copy of the project. You have to find "fork" button at the top of the GitHub project page https://github.com/ybogdanov/history-timeline such was that it will become _robbphoenix/history-timeline_. After that, you can [clone the repository](https://help.github.com/articles/cloning-a-repository/) you can have a local copy of the project on your computer. Once you are done, I will help with the later stuff.

Don't worry, if it appears too difficult to you, I will do the suggested fixes myself easily. Just want to have this exercise in place for the future contributions.

**Comment by robbphoenix** [comment]
I recommend you just create a guide with full instructions and post it in the "help" section if there is one. 

I'll try what you said to help add to the data bank in my spare time but request you to do the fixes.

**Comment by robbphoenix** [comment]
So I did what you said, I have a local copy on my computer, how do I go about adding in new historic figures (and linking them with wiki)?

**Comment by ybogdanov** [comment]
First, make sure `make data` command is working. After it works, it is a matter of minutes to make your corrections.

**Comment by ybogdanov** [comment]
I made the corrections and created a pull request. You can see it here https://github.com/ybogdanov/history-timeline/pull/12/files

See the changes on the site.

**Comment by ybogdanov** [comment]
@robbphoenix please confirm the issue is solved.

**Comment by robbphoenix** [comment]
The issue has been resolved. Thank you.
