### ISSUE TITLE
Add not-so famous person to timeline

### ISSUE THREAD

**Issue by chuckkahn** [ybogdanov/history-timeline#26]
Is there a way to manipulate the timeline display to add a not-so famous person?  (And then email that person a custom URL with said inclusion?)

**Comment by ybogdanov** [comment]
You can fork the project and then add that person to the `public/data/data_10000.js` manually in the given form same as other people listed there. You can then host our own copy of history timeline by setting up [Github Pages](https://pages.github.com/) for your own fork so the site is available under https://chuckkahn.github.io/history-timeline/

**Comment by chuckkahn** [comment]
I can't seem to edit data_10000.js from the github website, so I am cloning it to edit it from my desktop....

**Comment by ybogdanov** [comment]
Follow this guide on forking https://help.github.com/articles/fork-a-repo/

**Comment by chuckkahn** [comment]
How do I get Github Pages to point to my fork of index.html instead of using the output of the automatic page generator which loads README.md?

**Comment by ybogdanov** [comment]
You should create `gh-pages` branch. See the instruction here: https://help.github.com/articles/creating-project-pages-manually/

**Comment by chuckkahn** [comment]
I added my new entry to the top of the data_10000.js.  Did I do it right? 

https://raw.githubusercontent.com/chuckkahn/history-timeline/master/public/data/data_10000.js

**Comment by ybogdanov** [comment]
This change looks good https://github.com/chuckkahn/history-timeline/commit/b8a9cdf8057dfd71ce3f230deca89690354532f0
But you have to merge it to your `gh-pages` branch to have it reflected on the web. He will definitely shift Stephen King.

**Comment by chuckkahn** [comment]
Finally... finished.

**Comment by ybogdanov** [comment]
Nice!
